# === PostgreSQL Database Schema (database) v1 ===
# PostgreSQL database initialization on port 5432. Provides a single idempotent SQL init script (init.sql) that creates the `tasks` table with columns: id SERIAL PRIMARY KEY, title VARCHAR(255) NOT NULL, description TEXT, status VARCHAR(20) NOT NULL DEFAULT 'pending', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(). Includes a CHECK constraint on status enforcing ('pending', 'in_progress', 'done') and an automatic updated_at trigger function for defense-in-depth data integrity. This is a standalone schema definition with no application logic. The init script is executed on database initialization (e.g., Docker entrypoint mount to /docker-entrypoint-initdb.d/). Connection is via DATABASE_URL environment variable on port 5432. Satisfies AC1.

# Module invariants:
#   - The tasks table has exactly 6 columns: id, title, description, status, created_at, updated_at — no more, no fewer.
#   - Column 'id' is SERIAL PRIMARY KEY (int4, auto-incrementing, unique, NOT NULL). Values are non-contiguous; gaps are expected and valid.
#   - Column 'title' is VARCHAR(255) NOT NULL. Empty string '' is allowed by the schema but semantically discouraged (application-layer concern).
#   - Column 'description' is TEXT with no NOT NULL constraint. NULL represents absence of a description.
#   - Column 'status' is VARCHAR(20) NOT NULL DEFAULT 'pending' with CHECK constraint enforcing value IN ('pending', 'in_progress', 'done').
#   - Column 'created_at' is TIMESTAMPTZ NOT NULL DEFAULT NOW(). Set on INSERT, never modified after row creation.
#   - Column 'updated_at' is TIMESTAMPTZ NOT NULL DEFAULT NOW(). Set on INSERT via DEFAULT; automatically updated to NOW() on every UPDATE via the update_updated_at_column() trigger.
#   - The update_updated_at_column() trigger fires BEFORE UPDATE on each row, setting NEW.updated_at = NOW().
#   - All TIMESTAMPTZ values are stored internally in UTC by PostgreSQL regardless of session timezone settings.
#   - DEFAULT values (status='pending', created_at=NOW(), updated_at=NOW()) apply only on INSERT when the column is not explicitly provided.
#   - The init.sql script is fully idempotent: re-execution does not fail and does not modify existing data.
#   - psycopg2 type mapping: id -> int, title -> str, description -> Optional[str], status -> str, created_at -> datetime.datetime (tzinfo=UTC), updated_at -> datetime.datetime (tzinfo=UTC).
#   - The init.sql file is under 300 lines per operating procedure standards.

class TaskStatus(Enum):
    """Closed set of allowed task lifecycle states; enforced by backend validation and database CHECK-equivalent logic."""
    pending = "pending"
    in_progress = "in_progress"
    done = "done"

TaskId = primitive  # Integer surrogate key for a task row, generated by PostgreSQL SERIAL.

TaskTitle = primitive  # The title column of the tasks table. VARCHAR(255) NOT NULL. Maps to Python str via psycopg2.

TaskDescription = str | None

Timestamptz = primitive  # TIMESTAMPTZ column type. Stored in UTC by PostgreSQL regardless of session timezone. Maps to Python datetime.datetime (timezone-aware, tzinfo=UTC) via psycopg2. DEFAULT NOW() applies only on INSERT; updated_at is maintained by trigger on UPDATE.

class TaskRow:
    """Represents a single row in the tasks table as returned by a SELECT *. This is the canonical wire format for task data read from the database."""
    id: TaskId                               # required, Auto-generated SERIAL primary key.
    title: TaskTitle                         # required, Task title, VARCHAR(255) NOT NULL.
    description: TaskDescription = None      # optional, Task description, TEXT, nullable.
    status: TaskStatus                       # required, Task status, VARCHAR(20) NOT NULL DEFAULT 'pending'. Constrained by CHECK to ('pending', 'in_progress', 'done').
    created_at: Timestamptz                  # required, Row creation timestamp. DEFAULT NOW() on INSERT, never modified after creation.
    updated_at: Timestamptz                  # required, Last modification timestamp. DEFAULT NOW() on INSERT, automatically set to NOW() on UPDATE by trigger function update_updated_at_column().

class ConnectionConfig:
    """PostgreSQL connection parameters derived from DATABASE_URL environment variable. The database listens on port 5432."""
    database_url: str                        # required, regex(^postgresql://), Full PostgreSQL connection URI, e.g. 'postgresql://user:pass@host:5432/dbname'. Read from DATABASE_URL environment variable.
    port: int                                # required, range(value == 5432), PostgreSQL listener port. Fixed at 5432 for this deployment.

class InitScriptResult:
    """Result of executing the init.sql script against a PostgreSQL instance."""
    table_created: bool                      # required, True if the tasks table was created; false if it already existed (idempotent).
    trigger_created: bool                    # required, True if the update_updated_at_column trigger function and trigger were created; false if they already existed.
    check_constraint_present: bool           # required, True if the CHECK constraint on status column is verified present.

def execute_init_script(
    connection_config: ConnectionConfig,
) -> InitScriptResult:
    """
    Executes the idempotent init.sql script against the target PostgreSQL database. The script performs: (1) CREATE TABLE IF NOT EXISTS tasks with all specified columns, (2) adds CHECK constraint on status column for ('pending', 'in_progress', 'done'), (3) creates OR REPLACE the update_updated_at_column() trigger function, (4) creates the trigger on the tasks table IF NOT EXISTS. This function represents the database initialization entrypoint, typically invoked by Docker via /docker-entrypoint-initdb.d/init.sql mount.

    Preconditions:
      - PostgreSQL server is running and accepting connections on port 5432
      - DATABASE_URL environment variable is set with valid credentials
      - The target database exists (created by Docker POSTGRES_DB or equivalent)

    Postconditions:
      - Table 'tasks' exists with columns: id (SERIAL PK), title (VARCHAR(255) NOT NULL), description (TEXT nullable), status (VARCHAR(20) NOT NULL DEFAULT 'pending'), created_at (TIMESTAMPTZ NOT NULL DEFAULT NOW()), updated_at (TIMESTAMPTZ NOT NULL DEFAULT NOW())
      - CHECK constraint enforces status IN ('pending', 'in_progress', 'done')
      - Trigger function update_updated_at_column() exists and is attached to tasks table on BEFORE UPDATE
      - Pre-existing data in tasks table (if any) is not modified
      - Script is safe to re-execute (fully idempotent via IF NOT EXISTS and OR REPLACE)

    Errors:
      - connection_refused (ConnectionError): PostgreSQL server is not running or not reachable on the specified host:port
          host: Target hostname from DATABASE_URL
          port: 5432
      - authentication_failed (AuthenticationError): Credentials in DATABASE_URL are invalid or the user lacks CONNECT privilege
          user: Username from DATABASE_URL
      - database_not_found (DatabaseNotFoundError): The database name in DATABASE_URL does not exist on the server
          database: Database name from DATABASE_URL
      - insufficient_privileges (PermissionError): The connected user lacks CREATE TABLE, CREATE FUNCTION, or CREATE TRIGGER privileges on the target schema
          required_privileges: CREATE TABLE, CREATE FUNCTION, CREATE TRIGGER
      - sql_syntax_error (SQLSyntaxError): The init.sql script contains a syntax error (should not occur with a static, tested script)
          script: init.sql

    Side effects: none
    Idempotent: yes
    """
    ...

def verify_schema(
    connection_config: ConnectionConfig,
) -> InitScriptResult:
    """
    Verification function for contract tests. Connects to the database and introspects the information_schema and pg_catalog to confirm that: (1) the tasks table exists with the correct column definitions, (2) the CHECK constraint on status is present and correct, (3) the update_updated_at_column trigger is attached. This function is used exclusively in testing to validate postconditions of execute_init_script.

    Preconditions:
      - PostgreSQL server is running and accepting connections on port 5432
      - DATABASE_URL environment variable is set with valid credentials
      - execute_init_script has been invoked at least once (or init.sql has been applied)

    Postconditions:
      - No schema modifications are performed (read-only introspection)
      - Returns accurate reflection of current schema state

    Errors:
      - connection_refused (ConnectionError): PostgreSQL server is not running or not reachable
      - authentication_failed (AuthenticationError): Credentials in DATABASE_URL are invalid
      - introspection_query_failed (PermissionError): The user lacks SELECT privilege on information_schema or pg_catalog
          required_privileges: SELECT on information_schema, pg_catalog

    Side effects: none
    Idempotent: yes
    """
    ...

# ── REQUIRED EXPORTS ──────────────────────────────────
# Your implementation module MUST export ALL of these names
# with EXACTLY these spellings. Tests import them by name.
# __all__ = ['TaskStatus', 'TaskDescription', 'TaskRow', 'ConnectionConfig', 'InitScriptResult', 'execute_init_script', 'ConnectionError', 'AuthenticationError', 'DatabaseNotFoundError', 'SQLSyntaxError', 'verify_schema']
