"""Emission compliance tests for data_layer (auto-generated by pact)."""

from data_layer.data_layer import DataLayer


class TestEmissionCompliance:
    """Verify data_layer emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test_getToolBySlug_emits_events(self):
        """Method getToolBySlug emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = DataLayer(event_handler=handler)
        try:
            obj.getToolBySlug()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for getToolBySlug'
        assert len(completed) >= 1, 'No completed/error event for getToolBySlug'
        assert invoked[0].get("pact_key") == "PACT:data_layer:getToolBySlug"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_listComments_emits_events(self):
        """Method listComments emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = DataLayer(event_handler=handler)
        try:
            obj.listComments()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for listComments'
        assert len(completed) >= 1, 'No completed/error event for listComments'
        assert invoked[0].get("pact_key") == "PACT:data_layer:listComments"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_addComment_emits_events(self):
        """Method addComment emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = DataLayer(event_handler=handler)
        try:
            obj.addComment()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for addComment'
        assert len(completed) >= 1, 'No completed/error event for addComment'
        assert invoked[0].get("pact_key") == "PACT:data_layer:addComment"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = DataLayer(event_handler=handler)
        try:
            obj.getToolBySlug()
        except (TypeError, Exception):
            pass
        try:
            obj.listComments()
        except (TypeError, Exception):
            pass
        try:
            obj.addComment()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:data_layer:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = DataLayer()
        try:
            obj.getToolBySlug()
        except (TypeError, Exception):
            pass
        try:
            obj.listComments()
        except (TypeError, Exception):
            pass
        try:
            obj.addComment()
        except (TypeError, Exception):
            pass
