"""PostgreSQL Database Schema (database) component.

Provides idempotent SQL init script execution and schema verification
for the tasks table with all specified columns, constraints, and triggers.
"""

import logging
import re
import time
from enum import Enum
from dataclasses import dataclass, field
from typing import Optional

import psycopg2
import psycopg2.errors

_PACT_KEY = "PACT:3549b0:database"
logger = logging.getLogger(__name__)


class PactFormatter(logging.Formatter):
    """Formatter that injects the PACT log key into every record."""

    def format(self, record):
        record.pact_key = _PACT_KEY
        return super().format(record)


def _log(level: str, msg: str, **kwargs) -> None:
    """Log with PACT key embedded for production traceability."""
    getattr(logger, level)(f"[{_PACT_KEY}] {msg}", **kwargs)


# ---------------------------------------------------------------------------
# Custom Error Classes
# ---------------------------------------------------------------------------

class ConnectionError(Exception):
    """PostgreSQL server is not running or not reachable on the specified host:port."""
    pass


class AuthenticationError(Exception):
    """Credentials in DATABASE_URL are invalid or the user lacks CONNECT privilege."""
    pass


class DatabaseNotFoundError(Exception):
    """The database name in DATABASE_URL does not exist on the server."""
    pass


class SQLSyntaxError(Exception):
    """The init.sql script contains a syntax error."""
    pass


# ---------------------------------------------------------------------------
# Enum: TaskStatus
# ---------------------------------------------------------------------------

class TaskStatus(str, Enum):
    """Closed set of allowed task lifecycle states."""
    pending = "pending"
    in_progress = "in_progress"
    done = "done"


# ---------------------------------------------------------------------------
# Value Types
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class TaskId:
    """Integer surrogate key for a task row, generated by PostgreSQL SERIAL."""
    value: int

    def __post_init__(self) -> None:
        if not isinstance(self.value, int):
            raise TypeError(f"TaskId value must be int, got {type(self.value).__name__}")


@dataclass(frozen=True)
class TaskTitle:
    """The title column of the tasks table. VARCHAR(255) NOT NULL. Maps to Python str."""
    value: str

    def __post_init__(self) -> None:
        if not isinstance(self.value, str):
            raise TypeError(f"TaskTitle value must be str, got {type(self.value).__name__}")
        if len(self.value) < 1:
            raise ValueError("TaskTitle value must be at least 1 character, got empty string")
        if len(self.value) > 255:
            raise ValueError(
                f"TaskTitle value must be at most 255 characters, got {len(self.value)}"
            )


class TaskDescription:
    """Task description, TEXT, nullable. None represents SQL NULL."""

    def __init__(self, value: Optional[str] = None) -> None:
        self.value = value

    def __repr__(self) -> str:
        return f"TaskDescription(value={self.value!r})"

    def __str__(self) -> str:
        return str(self.value) if self.value is not None else "None"


_TIMESTAMPTZ_PATTERN = re.compile(
    r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$"
)


@dataclass(frozen=True)
class Timestamptz:
    """TIMESTAMPTZ column type. Stored in UTC by PostgreSQL."""
    value: str

    def __post_init__(self) -> None:
        if not isinstance(self.value, str):
            raise TypeError(f"Timestamptz value must be str, got {type(self.value).__name__}")
        if not _TIMESTAMPTZ_PATTERN.match(self.value):
            raise ValueError(
                f"Timestamptz value must be ISO 8601 with timezone, got: {self.value!r}"
            )


# ---------------------------------------------------------------------------
# Struct Types
# ---------------------------------------------------------------------------

@dataclass
class TaskRow:
    """Represents a single row in the tasks table as returned by SELECT *."""
    id: object  # TaskId or int
    title: object  # TaskTitle or str
    description: object = None  # TaskDescription or Optional[str]
    status: object = None  # TaskStatus or str
    created_at: object = None  # Timestamptz or datetime
    updated_at: object = None  # Timestamptz or datetime


@dataclass(frozen=True)
class ConnectionConfig:
    """PostgreSQL connection parameters derived from DATABASE_URL."""
    database_url: str
    port: int

    def __post_init__(self) -> None:
        if not isinstance(self.database_url, str) or not self.database_url.startswith("postgresql://"):
            raise ValueError(
                f"database_url must start with 'postgresql://', got: {self.database_url!r}"
            )
        if self.port != 5432:
            raise ValueError(f"port must be exactly 5432, got: {self.port}")


@dataclass
class InitScriptResult:
    """Result of executing the init.sql script against a PostgreSQL instance."""
    table_created: bool
    trigger_created: bool
    check_constraint_present: bool


# ---------------------------------------------------------------------------
# SQL Init Script
# ---------------------------------------------------------------------------

INIT_SQL = """
-- Idempotent init script for tasks table
-- Safe to re-execute: uses IF NOT EXISTS and OR REPLACE throughout

-- 1. Create the tasks table if it does not exist
CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Add CHECK constraint on status column (idempotent via DO block)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.check_constraints
        WHERE constraint_name = 'tasks_status_check'
    ) THEN
        ALTER TABLE tasks
            ADD CONSTRAINT tasks_status_check
            CHECK (status IN ('pending', 'in_progress', 'done'));
    END IF;
END
$$;

-- 3. Create or replace the trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. Create trigger if not exists (idempotent via DO block)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'set_updated_at'
    ) THEN
        CREATE TRIGGER set_updated_at
            BEFORE UPDATE ON tasks
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END
$$;
"""


# ---------------------------------------------------------------------------
# Helper: classify psycopg2 errors and re-raise as contract errors
# ---------------------------------------------------------------------------

def _classify_and_raise(exc: Exception) -> None:
    """Classify a psycopg2 exception into the contract error hierarchy."""
    msg = str(exc).lower()

    _log("error", f"Database error: {exc}")

    if isinstance(exc, psycopg2.OperationalError):
        if "password authentication failed" in msg or "authentication failed" in msg:
            raise AuthenticationError(str(exc)) from exc
        if "does not exist" in msg and "database" in msg:
            raise DatabaseNotFoundError(str(exc)) from exc
        # Default OperationalError -> connection issue
        raise ConnectionError(str(exc)) from exc

    if isinstance(exc, psycopg2.ProgrammingError):
        if "permission denied" in msg:
            raise PermissionError(str(exc)) from exc
        if "syntax error" in msg:
            raise SQLSyntaxError(str(exc)) from exc
        # ProgrammingError with permission denied
        raise PermissionError(str(exc)) from exc

    if isinstance(exc, psycopg2.Error):
        raise ConnectionError(str(exc)) from exc

    # Re-raise unknown
    raise exc


# ---------------------------------------------------------------------------
# Public Functions
# ---------------------------------------------------------------------------

def execute_init_script(
    connection_config: ConnectionConfig,
    event_handler=None,
    log_handler=None,
) -> InitScriptResult:
    """Execute the idempotent init.sql script against the target PostgreSQL database."""
    _emit = event_handler or (lambda event: None)
    _log_h = log_handler or (lambda level, msg, ctx: None)

    _emit({
        "pact_key": "PACT:3549b0:database:execute_init_script",
        "event": "invoked",
        "input_classification": ["connection_config"],
        "output_classification": [],
        "side_effects": [],
        "ts": time.time_ns(),
    })

    _log("info", "Executing init script")

    try:
        conn = psycopg2.connect(connection_config.database_url)
        try:
            conn.autocommit = True
            with conn.cursor() as cur:
                cur.execute(INIT_SQL)
            result = InitScriptResult(
                table_created=True,
                trigger_created=True,
                check_constraint_present=True,
            )
        finally:
            conn.close()
    except (ConnectionError, AuthenticationError, DatabaseNotFoundError,
            SQLSyntaxError, PermissionError):
        raise
    except Exception as exc:
        _classify_and_raise(exc)
        # unreachable but satisfies type checker
        raise  # pragma: no cover

    _emit({
        "pact_key": "PACT:3549b0:database:execute_init_script",
        "event": "completed",
        "input_classification": ["connection_config"],
        "output_classification": ["init_script_result"],
        "side_effects": ["schema_created"],
        "ts": time.time_ns(),
    })

    _log("info", "Init script executed successfully")
    return result


def verify_schema(
    connection_config: ConnectionConfig,
    event_handler=None,
    log_handler=None,
) -> InitScriptResult:
    """Verify the database schema by introspecting information_schema and pg_catalog."""
    _emit = event_handler or (lambda event: None)
    _log_h = log_handler or (lambda level, msg, ctx: None)

    _emit({
        "pact_key": "PACT:3549b0:database:verify_schema",
        "event": "invoked",
        "input_classification": ["connection_config"],
        "output_classification": [],
        "side_effects": [],
        "ts": time.time_ns(),
    })

    _log("info", "Verifying database schema")

    table_exists = False
    check_constraint_present = False
    trigger_exists = False

    try:
        conn = psycopg2.connect(connection_config.database_url)
        try:
            conn.autocommit = True
            with conn.cursor() as cur:
                # 1. Check if table exists
                cur.execute(
                    "SELECT EXISTS ("
                    "  SELECT 1 FROM information_schema.tables "
                    "  WHERE table_schema = 'public' AND table_name = 'tasks'"
                    ")"
                )
                row = cur.fetchone()
                table_exists = bool(row and row[0])

                # 2. Check if CHECK constraint exists
                cur.execute(
                    "SELECT EXISTS ("
                    "  SELECT 1 FROM information_schema.check_constraints "
                    "  WHERE constraint_name = 'tasks_status_check'"
                    ")"
                )
                row = cur.fetchone()
                check_constraint_present = bool(row and row[0])

                # 3. Check if trigger exists
                cur.execute(
                    "SELECT EXISTS ("
                    "  SELECT 1 FROM pg_trigger "
                    "  WHERE tgname = 'set_updated_at'"
                    ")"
                )
                row = cur.fetchone()
                trigger_exists = bool(row and row[0])
        finally:
            conn.close()
    except (ConnectionError, AuthenticationError, DatabaseNotFoundError,
            SQLSyntaxError, PermissionError):
        raise
    except Exception as exc:
        _classify_and_raise(exc)
        raise  # pragma: no cover

    result = InitScriptResult(
        table_created=table_exists,
        trigger_created=trigger_exists,
        check_constraint_present=check_constraint_present,
    )

    _emit({
        "pact_key": "PACT:3549b0:database:verify_schema",
        "event": "completed",
        "input_classification": ["connection_config"],
        "output_classification": ["init_script_result"],
        "side_effects": [],
        "ts": time.time_ns(),
    })

    _log("info", f"Schema verification complete: {result}")
    return result


# ---------------------------------------------------------------------------
# Required Exports
# ---------------------------------------------------------------------------

__all__ = [
    "TaskStatus",
    "TaskId",
    "TaskTitle",
    "TaskDescription",
    "Timestamptz",
    "TaskRow",
    "ConnectionConfig",
    "InitScriptResult",
    "execute_init_script",
    "verify_schema",
    "ConnectionError",
    "AuthenticationError",
    "DatabaseNotFoundError",
    "SQLSyntaxError",
]
