"""Emission compliance tests for root (auto-generated by pact)."""

from root.root import Root


class TestEmissionCompliance:
    """Verify root emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test_App_emits_events(self):
        """Method App emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.App()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for App'
        assert len(completed) >= 1, 'No completed/error event for App'
        assert invoked[0].get("pact_key") == "PACT:root:App"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_bootstrap_emits_events(self):
        """Method bootstrap emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.bootstrap()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for bootstrap'
        assert len(completed) >= 1, 'No completed/error event for bootstrap'
        assert invoked[0].get("pact_key") == "PACT:root:bootstrap"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_RootErrorFallback_emits_events(self):
        """Method RootErrorFallback emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.RootErrorFallback()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for RootErrorFallback'
        assert len(completed) >= 1, 'No completed/error event for RootErrorFallback'
        assert invoked[0].get("pact_key") == "PACT:root:RootErrorFallback"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.App()
        except (TypeError, Exception):
            pass
        try:
            obj.bootstrap()
        except (TypeError, Exception):
            pass
        try:
            obj.RootErrorFallback()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:root:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = Root()
        try:
            obj.App()
        except (TypeError, Exception):
            pass
        try:
            obj.bootstrap()
        except (TypeError, Exception):
            pass
        try:
            obj.RootErrorFallback()
        except (TypeError, Exception):
            pass
