"""Emission compliance tests for root (auto-generated by pact)."""

from root.root import Root


class TestEmissionCompliance:
    """Verify root emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test_config.get_config_emits_events(self):
        """Method config.get_config emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.config.get_config()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for config.get_config'
        assert len(completed) >= 1, 'No completed/error event for config.get_config'
        assert invoked[0].get("pact_key") == "PACT:root:config.get_config"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_db.get_conn_emits_events(self):
        """Method db.get_conn emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.db.get_conn()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for db.get_conn'
        assert len(completed) >= 1, 'No completed/error event for db.get_conn'
        assert invoked[0].get("pact_key") == "PACT:root:db.get_conn"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_db.execute_emits_events(self):
        """Method db.execute emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.db.execute()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for db.execute'
        assert len(completed) >= 1, 'No completed/error event for db.execute'
        assert invoked[0].get("pact_key") == "PACT:root:db.execute"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_db.execute_one_emits_events(self):
        """Method db.execute_one emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.db.execute_one()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for db.execute_one'
        assert len(completed) >= 1, 'No completed/error event for db.execute_one'
        assert invoked[0].get("pact_key") == "PACT:root:db.execute_one"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_db.close_conn_emits_events(self):
        """Method db.close_conn emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.db.close_conn()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for db.close_conn'
        assert len(completed) >= 1, 'No completed/error event for db.close_conn'
        assert invoked[0].get("pact_key") == "PACT:root:db.close_conn"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_shortener.generate_code_emits_events(self):
        """Method shortener.generate_code emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.shortener.generate_code()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for shortener.generate_code'
        assert len(completed) >= 1, 'No completed/error event for shortener.generate_code'
        assert invoked[0].get("pact_key") == "PACT:root:shortener.generate_code"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_shortener.shorten_url_emits_events(self):
        """Method shortener.shorten_url emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.shortener.shorten_url()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for shortener.shorten_url'
        assert len(completed) >= 1, 'No completed/error event for shortener.shorten_url'
        assert invoked[0].get("pact_key") == "PACT:root:shortener.shorten_url"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_shortener.resolve_and_track_emits_events(self):
        """Method shortener.resolve_and_track emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.shortener.resolve_and_track()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for shortener.resolve_and_track'
        assert len(completed) >= 1, 'No completed/error event for shortener.resolve_and_track'
        assert invoked[0].get("pact_key") == "PACT:root:shortener.resolve_and_track"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_shortener.list_links_emits_events(self):
        """Method shortener.list_links emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.shortener.list_links()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for shortener.list_links'
        assert len(completed) >= 1, 'No completed/error event for shortener.list_links'
        assert invoked[0].get("pact_key") == "PACT:root:shortener.list_links"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_main.post_shorten_emits_events(self):
        """Method main.post_shorten emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.main.post_shorten()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for main.post_shorten'
        assert len(completed) >= 1, 'No completed/error event for main.post_shorten'
        assert invoked[0].get("pact_key") == "PACT:root:main.post_shorten"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_main.get_redirect_emits_events(self):
        """Method main.get_redirect emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.main.get_redirect()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for main.get_redirect'
        assert len(completed) >= 1, 'No completed/error event for main.get_redirect'
        assert invoked[0].get("pact_key") == "PACT:root:main.get_redirect"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_main.get_links_emits_events(self):
        """Method main.get_links emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.main.get_links()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for main.get_links'
        assert len(completed) >= 1, 'No completed/error event for main.get_links'
        assert invoked[0].get("pact_key") == "PACT:root:main.get_links"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_main.get_index_emits_events(self):
        """Method main.get_index emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.main.get_index()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for main.get_index'
        assert len(completed) >= 1, 'No completed/error event for main.get_index'
        assert invoked[0].get("pact_key") == "PACT:root:main.get_index"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_main.startup_event_emits_events(self):
        """Method main.startup_event emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.main.startup_event()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for main.startup_event'
        assert len(completed) >= 1, 'No completed/error event for main.startup_event'
        assert invoked[0].get("pact_key") == "PACT:root:main.startup_event"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_main.shutdown_event_emits_events(self):
        """Method main.shutdown_event emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.main.shutdown_event()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for main.shutdown_event'
        assert len(completed) >= 1, 'No completed/error event for main.shutdown_event'
        assert invoked[0].get("pact_key") == "PACT:root:main.shutdown_event"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.config.get_config()
        except (TypeError, Exception):
            pass
        try:
            obj.db.get_conn()
        except (TypeError, Exception):
            pass
        try:
            obj.db.execute()
        except (TypeError, Exception):
            pass
        try:
            obj.db.execute_one()
        except (TypeError, Exception):
            pass
        try:
            obj.db.close_conn()
        except (TypeError, Exception):
            pass
        try:
            obj.shortener.generate_code()
        except (TypeError, Exception):
            pass
        try:
            obj.shortener.shorten_url()
        except (TypeError, Exception):
            pass
        try:
            obj.shortener.resolve_and_track()
        except (TypeError, Exception):
            pass
        try:
            obj.shortener.list_links()
        except (TypeError, Exception):
            pass
        try:
            obj.main.post_shorten()
        except (TypeError, Exception):
            pass
        try:
            obj.main.get_redirect()
        except (TypeError, Exception):
            pass
        try:
            obj.main.get_links()
        except (TypeError, Exception):
            pass
        try:
            obj.main.get_index()
        except (TypeError, Exception):
            pass
        try:
            obj.main.startup_event()
        except (TypeError, Exception):
            pass
        try:
            obj.main.shutdown_event()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:root:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = Root()
        try:
            obj.config.get_config()
        except (TypeError, Exception):
            pass
        try:
            obj.db.get_conn()
        except (TypeError, Exception):
            pass
        try:
            obj.db.execute()
        except (TypeError, Exception):
            pass
        try:
            obj.db.execute_one()
        except (TypeError, Exception):
            pass
        try:
            obj.db.close_conn()
        except (TypeError, Exception):
            pass
        try:
            obj.shortener.generate_code()
        except (TypeError, Exception):
            pass
        try:
            obj.shortener.shorten_url()
        except (TypeError, Exception):
            pass
        try:
            obj.shortener.resolve_and_track()
        except (TypeError, Exception):
            pass
        try:
            obj.shortener.list_links()
        except (TypeError, Exception):
            pass
        try:
            obj.main.post_shorten()
        except (TypeError, Exception):
            pass
        try:
            obj.main.get_redirect()
        except (TypeError, Exception):
            pass
        try:
            obj.main.get_links()
        except (TypeError, Exception):
            pass
        try:
            obj.main.get_index()
        except (TypeError, Exception):
            pass
        try:
            obj.main.startup_event()
        except (TypeError, Exception):
            pass
        try:
            obj.main.shutdown_event()
        except (TypeError, Exception):
            pass
