"""Emission compliance tests for home_page (auto-generated by pact)."""

from home_page.home_page import HomePage


class TestEmissionCompliance:
    """Verify home_page emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test_toQuickStartRow_emits_events(self):
        """Method toQuickStartRow emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = HomePage(event_handler=handler)
        try:
            obj.toQuickStartRow()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for toQuickStartRow'
        assert len(completed) >= 1, 'No completed/error event for toQuickStartRow'
        assert invoked[0].get("pact_key") == "PACT:home_page:toQuickStartRow"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_toDiagramNode_emits_events(self):
        """Method toDiagramNode emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = HomePage(event_handler=handler)
        try:
            obj.toDiagramNode()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for toDiagramNode'
        assert len(completed) >= 1, 'No completed/error event for toDiagramNode'
        assert invoked[0].get("pact_key") == "PACT:home_page:toDiagramNode"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_HomePage_emits_events(self):
        """Method HomePage emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = HomePage(event_handler=handler)
        try:
            obj.HomePage()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for HomePage'
        assert len(completed) >= 1, 'No completed/error event for HomePage'
        assert invoked[0].get("pact_key") == "PACT:home_page:HomePage"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_ClosedLoopDiagram_emits_events(self):
        """Method ClosedLoopDiagram emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = HomePage(event_handler=handler)
        try:
            obj.ClosedLoopDiagram()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for ClosedLoopDiagram'
        assert len(completed) >= 1, 'No completed/error event for ClosedLoopDiagram'
        assert invoked[0].get("pact_key") == "PACT:home_page:ClosedLoopDiagram"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = HomePage(event_handler=handler)
        try:
            obj.toQuickStartRow()
        except (TypeError, Exception):
            pass
        try:
            obj.toDiagramNode()
        except (TypeError, Exception):
            pass
        try:
            obj.HomePage()
        except (TypeError, Exception):
            pass
        try:
            obj.ClosedLoopDiagram()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:home_page:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = HomePage()
        try:
            obj.toQuickStartRow()
        except (TypeError, Exception):
            pass
        try:
            obj.toDiagramNode()
        except (TypeError, Exception):
            pass
        try:
            obj.HomePage()
        except (TypeError, Exception):
            pass
        try:
            obj.ClosedLoopDiagram()
        except (TypeError, Exception):
            pass
