"""Domain types for the database component."""
from __future__ import annotations

import enum
import re
from dataclasses import dataclass, field
from typing import Optional


class TaskStatus(enum.Enum):
    """Closed set of allowed task lifecycle states."""
    pending = "pending"
    in_progress = "in_progress"
    done = "done"


# Regex for TIMESTAMPTZ ISO 8601 with required timezone
_TIMESTAMPTZ_RE = re.compile(
    r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$'
)


class TaskId:
    """Integer surrogate key for a task row, generated by PostgreSQL SERIAL."""
    __slots__ = ('value',)

    def __init__(self, value: int) -> None:
        if not isinstance(value, int):
            raise TypeError(f"TaskId value must be int, got {type(value).__name__}")
        self.value = value

    def __repr__(self) -> str:
        return f"TaskId({self.value})"

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TaskId):
            return self.value == other.value
        if isinstance(other, int):
            return self.value == other
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self.value)


class TaskTitle:
    """The title column of the tasks table. VARCHAR(255) NOT NULL."""
    __slots__ = ('value',)

    def __init__(self, value: str) -> None:
        if not isinstance(value, str):
            raise TypeError(f"TaskTitle value must be str, got {type(value).__name__}")
        if len(value) < 1:
            raise ValueError("TaskTitle value must be at least 1 character")
        if len(value) > 255:
            raise ValueError(f"TaskTitle value must be at most 255 characters, got {len(value)}")
        self.value = value

    def __repr__(self) -> str:
        return f"TaskTitle({self.value!r})"

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TaskTitle):
            return self.value == other.value
        if isinstance(other, str):
            return self.value == other
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self.value)


class TaskDescription:
    """TEXT nullable column wrapper. None represents SQL NULL."""
    __slots__ = ('value',)

    def __init__(self, value: Optional[str] = None) -> None:
        if value is not None and not isinstance(value, str):
            raise TypeError(f"TaskDescription value must be str or None, got {type(value).__name__}")
        self.value = value

    def __repr__(self) -> str:
        return f"TaskDescription({self.value!r})"

    def __str__(self) -> str:
        return self.value if self.value is not None else ""

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TaskDescription):
            return self.value == other.value
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self.value)


class Timestamptz:
    """TIMESTAMPTZ column type. Validated against ISO 8601 with timezone."""
    __slots__ = ('value',)

    def __init__(self, value: str) -> None:
        if not isinstance(value, str):
            raise TypeError(f"Timestamptz value must be str, got {type(value).__name__}")
        if not _TIMESTAMPTZ_RE.match(value):
            raise ValueError(
                f"Timestamptz value must match ISO 8601 with timezone "
                f"(e.g. '2024-01-15T10:30:00Z'), got {value!r}"
            )
        self.value = value

    def __repr__(self) -> str:
        return f"Timestamptz({self.value!r})"

    def __eq__(self, other: object) -> bool:
        if isinstance(other, Timestamptz):
            return self.value == other.value
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self.value)


@dataclass
class ConnectionConfig:
    """PostgreSQL connection parameters."""
    database_url: str
    port: int

    def __post_init__(self) -> None:
        if not isinstance(self.database_url, str) or not self.database_url.startswith('postgresql://'):
            raise ValueError(
                f"database_url must start with 'postgresql://', got {self.database_url!r}"
            )
        if self.port != 5432:
            raise ValueError(f"port must be 5432, got {self.port}")


@dataclass
class TaskRow:
    """Represents a single row in the tasks table."""
    id: TaskId
    title: TaskTitle
    description: TaskDescription
    status: TaskStatus
    created_at: Timestamptz
    updated_at: Timestamptz


@dataclass
class InitScriptResult:
    """Result of executing or verifying the init.sql script."""
    table_created: bool
    trigger_created: bool
    check_constraint_present: bool
