# === FastAPI Backend API (backend) v1 ===
# A FastAPI application running on port 8000 that implements the task management REST API. Connects to PostgreSQL via DATABASE_URL env var using psycopg2.pool.ThreadedConnectionPool for connection pooling. Uses synchronous def endpoints with FastAPI's thread-pool executor. CORS middleware configured to allow frontend origin. Structured across main.py (app, CORS, lifespan/pool init), models.py (Pydantic schemas with StrEnum, validators, serializers), db.py (pool management, parameterized SQL query helpers with RealDictCursor), and routes.py (endpoint handlers with response_model/status_code decorators).

# Module invariants:
#   - All SQL queries use parameterized placeholders (%s); no string interpolation of user input into SQL.
#   - All public Python functions have complete type annotations (AC22).
#   - No source file exceeds 300 lines (AC25).
#   - TaskStatus enum is the single source of truth for valid status values; the set is {pending, in_progress, done}.
#   - created_at is immutable after INSERT; only updated_at changes on UPDATE.
#   - Empty or whitespace-only description strings are normalized to None before storage (A12).
#   - All timestamps returned in API responses are ISO 8601 with timezone offset (AC14).
#   - CORS middleware is configured to allow the frontend origin; configurable via environment or constant.
#   - Connection pool lifecycle is tied to FastAPI lifespan: initialized on startup, closed on shutdown.
#   - RealDictCursor is used for all database queries so rows are returned as dicts.
#   - PATCH semantics on PUT /tasks/{id}: model_fields_set determines which columns appear in the UPDATE SET clause.
#   - Title must be non-blank after whitespace stripping; blank titles are rejected with 422.
#   - DELETE is a hard delete; no soft-delete or archival.
#   - Test setup/teardown manages its own test data and does not depend on pre-existing database state (A10).
#   - Contract tests are conditionally skipped when DATABASE_URL environment variable is absent.

class TaskStatus(Enum):
    """Closed set of allowed task lifecycle states; enforced by backend validation and database CHECK-equivalent logic."""
    pending = "pending"
    in_progress = "in_progress"
    done = "done"

TaskTitle = primitive  # Non-blank, whitespace-stripped task title. Leading/trailing whitespace is stripped before validation; the result must have at least 1 character and at most 200 characters.

OptionalString = string | None

ISOTimestamp = primitive  # A datetime with timezone info, serialized to ISO 8601 string with timezone via Pydantic field_serializer calling isoformat(). Guarantees AC14 compliance. In Python, stored as datetime.datetime; in JSON, emitted as string like '2024-01-15T10:30:00+00:00'.

TaskId = primitive  # Integer surrogate key for a task row, generated by PostgreSQL SERIAL.

class TaskCreateRequest:
    """Request body for POST /tasks — creates a new task."""
    title: string                            # required, length(1..255), Task title. Must be non-empty, max 255 characters.
    description: OptionalString = null       # optional, Optional task description. Null if omitted or empty string submitted.
    status: TaskStatus = pending             # optional, Initial task status. Defaults to 'pending' if not provided.

class TaskUpdateRequest:
    """Request body for PUT /tasks/{id} — partial update (PATCH semantics). Only provided fields are modified; created_at is never affected."""
    title: string = None                     # optional, length(1..255), New title. If provided, must be non-empty, max 255 characters.
    description: OptionalString = None       # optional, New description. Explicit null clears the field.
    status: TaskStatus = None                # optional, New status. Must be a valid TaskStatus variant.

class TaskResponse:
    """Complete task object returned by all read/write endpoints. Timestamps are serialized as ISO 8601 with timezone via field_serializer."""
    id: TaskId                               # required, UUID v4 primary key.
    title: TaskTitle                         # required, Task title.
    description: OptionalString = None       # optional, Task description or None.
    status: TaskStatus                       # required, Current lifecycle state.
    created_at: ISOTimestamp                 # required, Creation timestamp, never modified after insert.
    updated_at: ISOTimestamp                 # required, Last-modification timestamp, set to NOW() on every update.

TaskListResponse = list[TaskResponse]
# JSON array of TaskResponse objects, ordered by created_at DESC.

class HealthResponse:
    """Response body for GET /health indicating service liveness."""
    status: string                           # required, custom(value == 'ok'), Always the literal string 'ok'.

class DeleteConfirmation:
    """Response body for DELETE /tasks/{id} on successful hard-delete (HTTP 200)."""
    detail: string                           # required, Confirmation message (e.g. 'Task deleted').
    id: TaskId                               # required, The id of the task that was deleted.

class ErrorDetail:
    """Standard error response body returned by HTTPException (FastAPI convention)."""
    detail: str                              # required, Human-readable error message.

class ValidationErrorResponse:
    """422 Unprocessable Entity response body produced by FastAPI/Pydantic validation failures."""
    detail: list                             # required, Array of validation error objects, each with loc, msg, and type fields per Pydantic v2 convention.

DatabaseURL = primitive  # PostgreSQL connection string read from DATABASE_URL environment variable.

class string:
    """Auto-stubbed type — referenced but not defined in contract 'backend'"""
    pass

def health_check() -> HealthResponse:
    """
    GET /health — Returns {'status': 'ok'} to confirm the service is running. No database interaction. (AC3)

    Postconditions:
      - Response body is exactly {'status': 'ok'}.
      - HTTP status code is 200.

    Side effects: none
    Idempotent: yes
    """
    ...

def list_tasks() -> TaskListResponse:
    """
    GET /tasks — Returns a JSON array of all tasks ordered by created_at DESC. Queries PostgreSQL via connection pool. (A3, AC7)

    Preconditions:
      - Connection pool is initialized (lifespan has completed startup).

    Postconditions:
      - Response is a JSON array (possibly empty).
      - Array elements conform to TaskResponse schema.
      - Array is ordered by created_at DESC.
      - HTTP status code is 200.
      - All timestamps are ISO 8601 with timezone.

    Errors:
      - database_unavailable (HTTPException): PostgreSQL connection pool is exhausted or database is unreachable.
          status_code: 500
          detail: Database connection error

    Side effects: none
    Idempotent: yes
    """
    ...

def create_task(
    task: TaskCreateRequest,
) -> TaskResponse:
    """
    POST /tasks — Creates a new task. Title is required, description optional (normalized to None if empty), status optional defaulting to 'pending'. Returns 201 with the full task object including server-generated id, created_at, updated_at. (A6, AC4-AC6)

    Preconditions:
      - Connection pool is initialized.
      - Request body is valid JSON.

    Postconditions:
      - HTTP status code is 201.
      - Response body conforms to TaskResponse schema.
      - response.id is a valid UUID v4.
      - response.title == stripped(input.title).
      - response.description is None if input.description was omitted, empty, or whitespace-only.
      - response.status == input.status if provided, else 'pending'.
      - response.created_at and response.updated_at are ISO 8601 with timezone.
      - A new row exists in the tasks table with matching id.

    Errors:
      - blank_title (ValidationErrorResponse): Title is missing, empty, or whitespace-only after stripping.
          status_code: 422
      - invalid_status (ValidationErrorResponse): Status value is not one of {pending, in_progress, done}.
          status_code: 422
      - database_unavailable (HTTPException): PostgreSQL connection pool is exhausted or database is unreachable.
          status_code: 500
          detail: Database connection error

    Side effects: none
    Idempotent: no
    """
    ...

def get_task(
    id: TaskId,
) -> TaskResponse:
    """
    GET /tasks/{id} — Returns a single task by its UUID. Returns 404 with detail message if not found. (AC8-AC9)

    Preconditions:
      - Connection pool is initialized.

    Postconditions:
      - HTTP status code is 200.
      - Response body conforms to TaskResponse schema.
      - response.id == input id.
      - All timestamps are ISO 8601 with timezone.

    Errors:
      - task_not_found (HTTPException): No task exists with the given id.
          status_code: 404
          detail: Task not found
      - invalid_id_format (ValidationErrorResponse): Path parameter is not a valid UUID.
          status_code: 422
      - database_unavailable (HTTPException): PostgreSQL connection pool is exhausted or database is unreachable.
          status_code: 500
          detail: Database connection error

    Side effects: none
    Idempotent: yes
    """
    ...

def update_task(
    id: TaskId,
    task: TaskUpdateRequest,
) -> TaskResponse:
    """
    PUT /tasks/{id} — PATCH semantics: only fields present in model_fields_set are updated. created_at is never modified. updated_at is set to NOW() server-side. Status validated against TaskStatus enum. Returns 404 if task not found. (A1, AC10-AC11)

    Preconditions:
      - Connection pool is initialized.
      - Request body is valid JSON.

    Postconditions:
      - HTTP status code is 200.
      - Response body conforms to TaskResponse schema.
      - response.id == input id.
      - For each field in task.model_fields_set: response.<field> == task.<field> (after normalization).
      - Fields NOT in task.model_fields_set retain their previous values.
      - response.created_at == previous created_at (never modified).
      - response.updated_at >= previous updated_at (set to NOW()).
      - All timestamps are ISO 8601 with timezone.

    Errors:
      - task_not_found (HTTPException): No task exists with the given id.
          status_code: 404
          detail: Task not found
      - invalid_status (ValidationErrorResponse): Status value is not one of {pending, in_progress, done}.
          status_code: 422
      - blank_title (ValidationErrorResponse): Title is provided but is empty or whitespace-only after stripping.
          status_code: 422
      - invalid_id_format (ValidationErrorResponse): Path parameter is not a valid UUID.
          status_code: 422
      - database_unavailable (HTTPException): PostgreSQL connection pool is exhausted or database is unreachable.
          status_code: 500
          detail: Database connection error

    Side effects: none
    Idempotent: yes
    """
    ...

def delete_task(
    id: TaskId,
) -> DeleteConfirmation:
    """
    DELETE /tasks/{id} — Hard-deletes the task. Returns 200 with JSON confirmation including the deleted task's id and a detail message. Returns 404 if not found. (AC12-AC13)

    Preconditions:
      - Connection pool is initialized.

    Postconditions:
      - HTTP status code is 200.
      - Response body conforms to DeleteConfirmation schema.
      - response.id == input id.
      - The row with the given id no longer exists in the tasks table.
      - response.detail is a non-empty confirmation string.

    Errors:
      - task_not_found (HTTPException): No task exists with the given id.
          status_code: 404
          detail: Task not found
      - invalid_id_format (ValidationErrorResponse): Path parameter is not a valid UUID.
          status_code: 422
      - database_unavailable (HTTPException): PostgreSQL connection pool is exhausted or database is unreachable.
          status_code: 500
          detail: Database connection error

    Side effects: none
    Idempotent: no
    """
    ...

def init_connection_pool(
    database_url: DatabaseURL,
    minconn: int = 1,
    maxconn: int = 10,
) -> None:
    """
    Initializes the psycopg2.pool.ThreadedConnectionPool during FastAPI lifespan startup. Reads DATABASE_URL from environment. Pool is stored as module-level or app-state reference for use by db.py helpers.

    Preconditions:
      - DATABASE_URL environment variable is set.
      - PostgreSQL server is reachable.

    Postconditions:
      - ThreadedConnectionPool is created and stored for use by query helpers.
      - At least minconn connections are established.

    Errors:
      - invalid_database_url (RuntimeError): DATABASE_URL is missing or not a valid PostgreSQL URI.
          detail: DATABASE_URL environment variable is required and must be a valid PostgreSQL URI.
      - connection_failed (RuntimeError): Cannot establish initial connection to PostgreSQL.
          detail: Failed to connect to PostgreSQL.

    Side effects: none
    Idempotent: no
    """
    ...

def close_connection_pool() -> None:
    """
    Closes the psycopg2.pool.ThreadedConnectionPool during FastAPI lifespan shutdown. Releases all connections back to PostgreSQL.

    Preconditions:
      - Connection pool was previously initialized.

    Postconditions:
      - All pooled connections are closed.
      - Pool reference is cleared.

    Side effects: none
    Idempotent: yes
    """
    ...

def get_connection() -> any:
    """
    Context manager that borrows a connection from the ThreadedConnectionPool, yields it, and returns it to the pool on exit. Uses RealDictCursor for all operations. Commits on clean exit, rolls back on exception.

    Preconditions:
      - Connection pool is initialized.

    Postconditions:
      - On normal exit: transaction is committed and connection is returned to pool.
      - On exception: transaction is rolled back and connection is returned to pool.

    Errors:
      - pool_exhausted (RuntimeError): All connections in the pool are in use and maxconn is reached.
          detail: Connection pool exhausted.

    Side effects: none
    Idempotent: yes
    """
    ...

def db_list_tasks() -> list:
    """
    Database helper: SELECT * FROM tasks ORDER BY created_at DESC. Returns list of RealDictRow dicts. Pydantic model construction happens in the route layer.

    Preconditions:
      - Connection pool is initialized.
      - tasks table exists in the database.

    Postconditions:
      - Returns a list of dicts, each containing keys: id, title, description, status, created_at, updated_at.
      - List is ordered by created_at DESC.
      - Timestamps are Python datetime objects with tzinfo.

    Errors:
      - query_error (RuntimeError): SQL execution fails (e.g., table does not exist, connection interrupted).

    Side effects: none
    Idempotent: yes
    """
    ...

def db_create_task(
    title: str,
    description: OptionalString,
    status: str,
) -> dict:
    """
    Database helper: INSERT INTO tasks (title, description, status) VALUES (%s, %s, %s) RETURNING *. Uses parameterized SQL exclusively.

    Preconditions:
      - Connection pool is initialized.
      - tasks table exists.
      - title is non-empty.
      - status is one of {pending, in_progress, done}.

    Postconditions:
      - Returns a dict with keys: id, title, description, status, created_at, updated_at.
      - id is a new UUID v4 generated by PostgreSQL.
      - created_at and updated_at are set by PostgreSQL NOW().

    Errors:
      - query_error (RuntimeError): SQL execution fails.

    Side effects: none
    Idempotent: no
    """
    ...

def db_get_task(
    task_id: str,
) -> dict:
    """
    Database helper: SELECT * FROM tasks WHERE id = %s. Returns a dict or None if not found.

    Preconditions:
      - Connection pool is initialized.
      - tasks table exists.
      - task_id is a valid UUID string.

    Postconditions:
      - Returns a dict with task columns if found, or None if no row matches.

    Errors:
      - query_error (RuntimeError): SQL execution fails.

    Side effects: none
    Idempotent: yes
    """
    ...

def db_update_task(
    task_id: str,
    fields: dict,
) -> dict:
    """
    Database helper: Builds a dynamic UPDATE SET clause from the provided fields dict (derived from model_fields_set). Always appends updated_at=NOW(). Uses parameterized SQL. Returns the updated row dict or None if not found.

    Preconditions:
      - Connection pool is initialized.
      - tasks table exists.
      - task_id is a valid UUID string.
      - fields keys are a subset of {title, description, status}.
      - If 'title' is in fields, its value is a non-empty string.
      - If 'status' is in fields, its value is one of {pending, in_progress, done}.

    Postconditions:
      - Returns a dict with all task columns reflecting the update, or None if no row matched.
      - updated_at in the returned dict reflects NOW() at execution time.
      - created_at is unchanged.
      - Only columns in fields (plus updated_at) were modified.

    Errors:
      - query_error (RuntimeError): SQL execution fails.

    Side effects: none
    Idempotent: yes
    """
    ...

def db_delete_task(
    task_id: str,
) -> dict:
    """
    Database helper: DELETE FROM tasks WHERE id = %s RETURNING id. Returns the deleted id or None if not found.

    Preconditions:
      - Connection pool is initialized.
      - tasks table exists.
      - task_id is a valid UUID string.

    Postconditions:
      - Returns a dict with 'id' key if a row was deleted, or None if no row matched.
      - If a row was deleted, it no longer exists in the tasks table.

    Errors:
      - query_error (RuntimeError): SQL execution fails.

    Side effects: none
    Idempotent: no
    """
    ...

# ── REQUIRED EXPORTS ──────────────────────────────────
# Your implementation module MUST export ALL of these names
# with EXACTLY these spellings. Tests import them by name.
# __all__ = ['TaskStatus', 'OptionalString', 'TaskCreateRequest', 'TaskUpdateRequest', 'TaskResponse', 'TaskListResponse', 'HealthResponse', 'DeleteConfirmation', 'ErrorDetail', 'ValidationErrorResponse', 'string', 'health_check', 'list_tasks', 'HTTPException', 'create_task', 'get_task', 'update_task', 'delete_task', 'init_connection_pool', 'close_connection_pool', 'get_connection', 'db_list_tasks', 'db_create_task', 'db_get_task', 'db_update_task', 'db_delete_task']
