"""Emission compliance tests for database (auto-generated by pact)."""

from database.database import Database


class TestEmissionCompliance:
    """Verify database emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test_execute_init_script_emits_events(self):
        """Method execute_init_script emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Database(event_handler=handler)
        try:
            obj.execute_init_script()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for execute_init_script'
        assert len(completed) >= 1, 'No completed/error event for execute_init_script'
        assert invoked[0].get("pact_key") == "PACT:database:execute_init_script"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_verify_schema_emits_events(self):
        """Method verify_schema emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Database(event_handler=handler)
        try:
            obj.verify_schema()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for verify_schema'
        assert len(completed) >= 1, 'No completed/error event for verify_schema'
        assert invoked[0].get("pact_key") == "PACT:database:verify_schema"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = Database(event_handler=handler)
        try:
            obj.execute_init_script()
        except (TypeError, Exception):
            pass
        try:
            obj.verify_schema()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:database:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = Database()
        try:
            obj.execute_init_script()
        except (TypeError, Exception):
            pass
        try:
            obj.verify_schema()
        except (TypeError, Exception):
            pass
