"""Emission compliance tests for app_shell (auto-generated by pact)."""

from app_shell.app_shell import AppShell


class TestEmissionCompliance:
    """Verify app_shell emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test_createConvexClient_emits_events(self):
        """Method createConvexClient emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = AppShell(event_handler=handler)
        try:
            obj.createConvexClient()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for createConvexClient'
        assert len(completed) >= 1, 'No completed/error event for createConvexClient'
        assert invoked[0].get("pact_key") == "PACT:app_shell:createConvexClient"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_isValidToolSlug_emits_events(self):
        """Method isValidToolSlug emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = AppShell(event_handler=handler)
        try:
            obj.isValidToolSlug()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for isValidToolSlug'
        assert len(completed) >= 1, 'No completed/error event for isValidToolSlug'
        assert invoked[0].get("pact_key") == "PACT:app_shell:isValidToolSlug"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_toolPath_emits_events(self):
        """Method toolPath emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = AppShell(event_handler=handler)
        try:
            obj.toolPath()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for toolPath'
        assert len(completed) >= 1, 'No completed/error event for toolPath'
        assert invoked[0].get("pact_key") == "PACT:app_shell:toolPath"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_renderApp_emits_events(self):
        """Method renderApp emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = AppShell(event_handler=handler)
        try:
            obj.renderApp()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for renderApp'
        assert len(completed) >= 1, 'No completed/error event for renderApp'
        assert invoked[0].get("pact_key") == "PACT:app_shell:renderApp"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_renderLayout_emits_events(self):
        """Method renderLayout emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = AppShell(event_handler=handler)
        try:
            obj.renderLayout()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for renderLayout'
        assert len(completed) >= 1, 'No completed/error event for renderLayout'
        assert invoked[0].get("pact_key") == "PACT:app_shell:renderLayout"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_renderSidebar_emits_events(self):
        """Method renderSidebar emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = AppShell(event_handler=handler)
        try:
            obj.renderSidebar()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for renderSidebar'
        assert len(completed) >= 1, 'No completed/error event for renderSidebar'
        assert invoked[0].get("pact_key") == "PACT:app_shell:renderSidebar"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_projectToolDefToSidebarItem_emits_events(self):
        """Method projectToolDefToSidebarItem emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = AppShell(event_handler=handler)
        try:
            obj.projectToolDefToSidebarItem()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for projectToolDefToSidebarItem'
        assert len(completed) >= 1, 'No completed/error event for projectToolDefToSidebarItem'
        assert invoked[0].get("pact_key") == "PACT:app_shell:projectToolDefToSidebarItem"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = AppShell(event_handler=handler)
        try:
            obj.createConvexClient()
        except (TypeError, Exception):
            pass
        try:
            obj.isValidToolSlug()
        except (TypeError, Exception):
            pass
        try:
            obj.toolPath()
        except (TypeError, Exception):
            pass
        try:
            obj.renderApp()
        except (TypeError, Exception):
            pass
        try:
            obj.renderLayout()
        except (TypeError, Exception):
            pass
        try:
            obj.renderSidebar()
        except (TypeError, Exception):
            pass
        try:
            obj.projectToolDefToSidebarItem()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:app_shell:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = AppShell()
        try:
            obj.createConvexClient()
        except (TypeError, Exception):
            pass
        try:
            obj.isValidToolSlug()
        except (TypeError, Exception):
            pass
        try:
            obj.toolPath()
        except (TypeError, Exception):
            pass
        try:
            obj.renderApp()
        except (TypeError, Exception):
            pass
        try:
            obj.renderLayout()
        except (TypeError, Exception):
            pass
        try:
            obj.renderSidebar()
        except (TypeError, Exception):
            pass
        try:
            obj.projectToolDefToSidebarItem()
        except (TypeError, Exception):
            pass
