"""Emission compliance tests for root (auto-generated by pact)."""

from root.root import Root


class TestEmissionCompliance:
    """Verify root emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test_validate_create_task_emits_events(self):
        """Method validate_create_task emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.validate_create_task()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for validate_create_task'
        assert len(completed) >= 1, 'No completed/error event for validate_create_task'
        assert invoked[0].get("pact_key") == "PACT:root:validate_create_task"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_validate_update_task_emits_events(self):
        """Method validate_update_task emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.validate_update_task()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for validate_update_task'
        assert len(completed) >= 1, 'No completed/error event for validate_update_task'
        assert invoked[0].get("pact_key") == "PACT:root:validate_update_task"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_create_task_emits_events(self):
        """Method create_task emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.create_task()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for create_task'
        assert len(completed) >= 1, 'No completed/error event for create_task'
        assert invoked[0].get("pact_key") == "PACT:root:create_task"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_list_tasks_emits_events(self):
        """Method list_tasks emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.list_tasks()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for list_tasks'
        assert len(completed) >= 1, 'No completed/error event for list_tasks'
        assert invoked[0].get("pact_key") == "PACT:root:list_tasks"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_get_task_emits_events(self):
        """Method get_task emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.get_task()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for get_task'
        assert len(completed) >= 1, 'No completed/error event for get_task'
        assert invoked[0].get("pact_key") == "PACT:root:get_task"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_update_task_emits_events(self):
        """Method update_task emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.update_task()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for update_task'
        assert len(completed) >= 1, 'No completed/error event for update_task'
        assert invoked[0].get("pact_key") == "PACT:root:update_task"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_delete_task_emits_events(self):
        """Method delete_task emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.delete_task()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for delete_task'
        assert len(completed) >= 1, 'No completed/error event for delete_task'
        assert invoked[0].get("pact_key") == "PACT:root:delete_task"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_get_endpoint_contracts_emits_events(self):
        """Method get_endpoint_contracts emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.get_endpoint_contracts()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for get_endpoint_contracts'
        assert len(completed) >= 1, 'No completed/error event for get_endpoint_contracts'
        assert invoked[0].get("pact_key") == "PACT:root:get_endpoint_contracts"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_task_to_dict_emits_events(self):
        """Method task_to_dict emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.task_to_dict()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for task_to_dict'
        assert len(completed) >= 1, 'No completed/error event for task_to_dict'
        assert invoked[0].get("pact_key") == "PACT:root:task_to_dict"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_task_from_dict_emits_events(self):
        """Method task_from_dict emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.task_from_dict()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for task_from_dict'
        assert len(completed) >= 1, 'No completed/error event for task_from_dict'
        assert invoked[0].get("pact_key") == "PACT:root:task_from_dict"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = Root(event_handler=handler)
        try:
            obj.validate_create_task()
        except (TypeError, Exception):
            pass
        try:
            obj.validate_update_task()
        except (TypeError, Exception):
            pass
        try:
            obj.create_task()
        except (TypeError, Exception):
            pass
        try:
            obj.list_tasks()
        except (TypeError, Exception):
            pass
        try:
            obj.get_task()
        except (TypeError, Exception):
            pass
        try:
            obj.update_task()
        except (TypeError, Exception):
            pass
        try:
            obj.delete_task()
        except (TypeError, Exception):
            pass
        try:
            obj.get_endpoint_contracts()
        except (TypeError, Exception):
            pass
        try:
            obj.task_to_dict()
        except (TypeError, Exception):
            pass
        try:
            obj.task_from_dict()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:root:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = Root()
        try:
            obj.validate_create_task()
        except (TypeError, Exception):
            pass
        try:
            obj.validate_update_task()
        except (TypeError, Exception):
            pass
        try:
            obj.create_task()
        except (TypeError, Exception):
            pass
        try:
            obj.list_tasks()
        except (TypeError, Exception):
            pass
        try:
            obj.get_task()
        except (TypeError, Exception):
            pass
        try:
            obj.update_task()
        except (TypeError, Exception):
            pass
        try:
            obj.delete_task()
        except (TypeError, Exception):
            pass
        try:
            obj.get_endpoint_contracts()
        except (TypeError, Exception):
            pass
        try:
            obj.task_to_dict()
        except (TypeError, Exception):
            pass
        try:
            obj.task_from_dict()
        except (TypeError, Exception):
            pass
