# === React Frontend SPA (frontend) v1 ===
# A React + Vite + TypeScript single-page application running on port 5173 that provides the task management UI. Communicates with the backend exclusively via HTTP REST API using VITE_API_URL env var (defaulting to http://localhost:8000). Structured across six modules: types.ts (canonical type mirrors), api.ts (typed fetch wrappers), App.tsx (state orchestration), TaskList.tsx, TaskItem.tsx (display + inline edit), TaskForm.tsx (create form). All files kept under 300 lines. No shared code with backend.

# Module invariants:
#   - All backend communication is exclusively via HTTP REST through api.ts — no direct fetch calls from components
#   - VITE_API_URL is the sole configuration point for backend URL; defaults to http://localhost:8000
#   - No page reloads — all state mutations are SPA-style via React useState/useEffect (A11)
#   - Empty description strings from the create form are sent as null to the backend (A12)
#   - Task status badge colors are deterministic: pending=grey, in_progress=blue, done=green (AC15-AC16)
#   - All non-ok HTTP responses are converted to ApiError with parsed detail before propagating to callers
#   - TaskItem toggles between display mode and inline edit form mode — no separate edit page (AC18)
#   - Delete success triggers immediate removal from local tasks state without waiting for re-fetch (AC19)
#   - No code is shared between frontend and backend modules (AC26)
#   - All source files are kept under 300 lines (AC25)
#   - Local tasks state is the single source of truth for rendered UI — patched optimistically from mutation responses
#   - The six prescribed modules are: types.ts, api.ts, App.tsx, TaskList.tsx, TaskItem.tsx, TaskForm.tsx

TaskId = primitive  # Integer surrogate key for a task row, generated by PostgreSQL SERIAL.

class TaskStatus(Enum):
    """Closed set of allowed task lifecycle states; enforced by backend validation and database CHECK-equivalent logic."""
    pending = "pending"
    in_progress = "in_progress"
    done = "done"

class Task:
    """Complete task resource representation returned by all GET/POST/PUT endpoints; mirrors the database row with timestamps serialized as ISO strings."""
    id: TaskId                               # required, Auto-generated primary key.
    title: string                            # required, length(1..255), Human-readable task title. Max 255 characters.
    description: OptionalString              # required, Free-text task description. Null when not provided.
    status: TaskStatus                       # required, Current lifecycle state of the task.
    created_at: Timestamp                    # required, Immutable creation timestamp set by the database on INSERT.
    updated_at: Timestamp                    # required, Last-modification timestamp set by the backend on every UPDATE.

OptionalStr = str | None

class TaskCreateRequest:
    """Request body for POST /tasks — creates a new task."""
    title: string                            # required, length(1..255), Task title. Must be non-empty, max 255 characters.
    description: OptionalString = null       # optional, Optional task description. Null if omitted or empty string submitted.
    status: TaskStatus = pending             # optional, Initial task status. Defaults to 'pending' if not provided.

class TaskUpdateRequest:
    """Request body for PUT /tasks/{id} — partial update (PATCH semantics). Only provided fields are modified; created_at is never affected."""
    title: string = None                     # optional, length(1..255), New title. If provided, must be non-empty, max 255 characters.
    description: OptionalString = None       # optional, New description. Explicit null clears the field.
    status: TaskStatus = None                # optional, New status. Must be a valid TaskStatus variant.

class ErrorResponse:
    """Standard error envelope returned on 404 (and other error codes) with a human-readable detail message."""
    detail: string                           # required, Human-readable error description (e.g. 'Task not found').

class DeleteConfirmation:
    """Response body for DELETE /tasks/{id} on successful hard-delete (HTTP 200)."""
    detail: string                           # required, Confirmation message (e.g. 'Task deleted').
    id: TaskId                               # required, The id of the task that was deleted.

class HealthResponse:
    """Response body for GET /health indicating service liveness."""
    status: string                           # required, custom(value == 'ok'), Always the literal string 'ok'.

class ApiError:
    """Frontend-specific error class extending Error. Thrown by api.ts functions when the backend returns a non-ok HTTP response. Captures HTTP status code and parsed detail message."""
    message: str                             # required, Error message, typically the parsed ErrorResponse.detail from the backend
    statusCode: int                          # required, range(100 <= value <= 599), HTTP status code from the failed response
    detail: str                              # required, Parsed detail string from the backend ErrorResponse body

class TaskListProps:
    """Props interface for the TaskList component. Defined in components/TaskList.tsx."""
    tasks: list                              # required, Array of Task objects to render
    onUpdate: str                            # required, Callback signature: (id: TaskId, data: TaskUpdateRequest) => Promise<void>. Called when a task is edited inline and saved.
    onDelete: str                            # required, Callback signature: (id: TaskId) => Promise<void>. Called when the delete button is clicked for a task.

class TaskItemProps:
    """Props interface for the TaskItem component. Defined in components/TaskItem.tsx. Manages display mode vs inline edit form mode toggle."""
    task: Task                               # required, The task to display and allow editing of
    onUpdate: str                            # required, Callback signature: (id: TaskId, data: TaskUpdateRequest) => Promise<void>. Invoked when user confirms inline edit.
    onDelete: str                            # required, Callback signature: (id: TaskId) => Promise<void>. Invoked when user clicks delete button.

class TaskFormProps:
    """Props interface for the TaskForm component. Defined in components/TaskForm.tsx."""
    onCreate: str                            # required, Callback signature: (data: TaskCreateRequest) => Promise<void>. Invoked when user submits the create task form.

class ImportMetaEnv:
    """Vite environment type augmentation. Declared in src/env.d.ts for compile-time safety of environment variables."""
    VITE_API_URL: str = http://localhost:8000 # optional, Base URL for the backend API. Resolved via import.meta.env.VITE_API_URL, defaults to 'http://localhost:8000' when not set.

class StatusBadgeColorMap:
    """Mapping from TaskStatus to CSS badge color class names used in TaskItem rendering."""
    pending: str                             # required, Grey badge color for pending status
    in_progress: str                         # required, Blue badge color for in_progress status
    done: str                                # required, Green badge color for done status

Timestamp = primitive  # ISO 8601 datetime string with timezone (e.g. '2025-01-15T12:00:00+00:00'). Stored as TIMESTAMPTZ in DB, serialized as string over the wire.

OptionalString = string | None

class string:
    """Auto-stubbed type — referenced but not defined in contract 'frontend'"""
    pass

async def fetchTasks() -> list:
    """
    Fetches all tasks from GET /tasks endpoint. Returns the full task list as an array. Used by App.tsx on mount and after mutations to synchronize local state.

    Preconditions:
      - BASE_URL is resolvable (import.meta.env.VITE_API_URL or default http://localhost:8000)
      - Backend API is reachable at BASE_URL

    Postconditions:
      - Returns an array of Task objects, each with all six fields populated
      - Array may be empty if no tasks exist
      - Tasks are ordered as returned by the backend (by id ascending)

    Errors:
      - network_error (ApiError): Backend is unreachable or network timeout occurs
          statusCode: 0
          detail: Network error or backend unreachable
      - server_error (ApiError): Backend returns HTTP 5xx status
          statusCode: 500
          detail: Parsed from ErrorResponse.detail

    Side effects: none
    Idempotent: yes
    """
    ...

async def createTask(
    data: TaskCreateRequest,
) -> Task:
    """
    Creates a new task via POST /tasks. Sends TaskCreateRequest as JSON body. Returns the newly created Task with backend-assigned id, created_at, and updated_at.

    Preconditions:
      - BASE_URL is resolvable
      - data.title is non-empty and at most 200 characters
      - data.description is null or at most 1000 characters
      - data.status is a valid TaskStatus variant if provided

    Postconditions:
      - Returned Task has a new positive integer id assigned by backend
      - Returned Task.title matches data.title
      - Returned Task.description matches data.description
      - Returned Task.status matches data.status or 'pending' if status was not provided
      - Returned Task.created_at and updated_at are valid ISO 8601 timestamps

    Errors:
      - validation_error (ApiError): Backend rejects the payload due to validation failure (e.g. empty title, title > 200 chars)
          statusCode: 422
          detail: Parsed validation error detail from backend
      - network_error (ApiError): Backend is unreachable or network timeout occurs
          statusCode: 0
          detail: Network error or backend unreachable
      - server_error (ApiError): Backend returns HTTP 5xx status
          statusCode: 500
          detail: Parsed from ErrorResponse.detail

    Side effects: none
    Idempotent: no
    """
    ...

async def updateTask(
    id: TaskId,
    data: TaskUpdateRequest,
) -> Task:
    """
    Updates an existing task via PUT /tasks/{id}. Sends TaskUpdateRequest as JSON body containing only changed fields. Returns the fully updated Task.

    Preconditions:
      - BASE_URL is resolvable
      - id is a positive integer referencing an existing task
      - data contains at least one field (title, description, or status)
      - If data.title is present, it is non-empty and at most 200 characters
      - If data.description is present and non-null, it is at most 1000 characters

    Postconditions:
      - Returned Task.id equals the input id
      - Returned Task reflects the applied updates
      - Returned Task.updated_at is >= the previous updated_at value
      - Fields not included in data remain unchanged from their prior values

    Errors:
      - not_found (ApiError): No task exists with the given id
          statusCode: 404
          detail: Task not found
      - validation_error (ApiError): Backend rejects the payload due to validation failure
          statusCode: 422
          detail: Parsed validation error detail from backend
      - network_error (ApiError): Backend is unreachable or network timeout occurs
          statusCode: 0
          detail: Network error or backend unreachable
      - server_error (ApiError): Backend returns HTTP 5xx status
          statusCode: 500
          detail: Parsed from ErrorResponse.detail

    Side effects: none
    Idempotent: yes
    """
    ...

async def deleteTask(
    id: TaskId,
) -> DeleteConfirmation:
    """
    Deletes a task via DELETE /tasks/{id}. Returns DeleteConfirmation on success. App.tsx removes the task from local state immediately upon success (AC19).

    Preconditions:
      - BASE_URL is resolvable
      - id is a positive integer referencing an existing task

    Postconditions:
      - Returned DeleteConfirmation.message confirms deletion
      - The task with the given id no longer exists in the backend
      - Subsequent fetchTasks calls will not include the deleted task

    Errors:
      - not_found (ApiError): No task exists with the given id
          statusCode: 404
          detail: Task not found
      - network_error (ApiError): Backend is unreachable or network timeout occurs
          statusCode: 0
          detail: Network error or backend unreachable
      - server_error (ApiError): Backend returns HTTP 5xx status
          statusCode: 500
          detail: Parsed from ErrorResponse.detail

    Side effects: none
    Idempotent: yes
    """
    ...

async def healthCheck() -> HealthResponse:
    """
    Checks backend availability via GET /health. Returns HealthResponse with status field. Used to verify backend connectivity.

    Preconditions:
      - BASE_URL is resolvable

    Postconditions:
      - Returned HealthResponse.status is 'healthy' when backend and database are operational

    Errors:
      - network_error (ApiError): Backend is unreachable or network timeout occurs
          statusCode: 0
          detail: Network error or backend unreachable
      - server_error (ApiError): Backend returns HTTP 5xx (e.g. database connection failure)
          statusCode: 500
          detail: Parsed from ErrorResponse.detail

    Side effects: none
    Idempotent: yes
    """
    ...

async def App.handleCreate(
    data: TaskCreateRequest,
) -> None:
    """
    App.tsx callback passed as TaskFormProps.onCreate. Calls createTask with the form data, then prepends the returned Task to the local tasks state array. No page reload (A11).

    Preconditions:
      - data.title is non-empty

    Postconditions:
      - Local tasks state array contains the newly created Task
      - UI re-renders to display the new task without page reload

    Errors:
      - create_failed (ApiError): createTask throws ApiError

    Side effects: none
    Idempotent: no
    """
    ...

async def App.handleUpdate(
    id: TaskId,
    data: TaskUpdateRequest,
) -> None:
    """
    App.tsx callback passed as TaskListProps.onUpdate and TaskItemProps.onUpdate. Calls updateTask, then replaces the matching task in local state with the returned Task. No page reload (A11).

    Preconditions:
      - A task with the given id exists in local tasks state

    Postconditions:
      - The task with the given id in local state is replaced with the backend response
      - UI re-renders to reflect updated task fields without page reload

    Errors:
      - update_failed (ApiError): updateTask throws ApiError

    Side effects: none
    Idempotent: yes
    """
    ...

async def App.handleDelete(
    id: TaskId,
) -> None:
    """
    App.tsx callback passed as TaskListProps.onDelete and TaskItemProps.onDelete. Calls deleteTask, then removes the task from local state for immediate UI removal (AC19). No page reload (A11).

    Preconditions:
      - A task with the given id exists in local tasks state

    Postconditions:
      - The task with the given id is removed from local tasks state
      - UI re-renders without the deleted task, no page reload

    Errors:
      - delete_failed (ApiError): deleteTask throws ApiError

    Side effects: none
    Idempotent: yes
    """
    ...

async def App.useEffectFetchOnMount() -> None:
    """
    useEffect hook in App.tsx that calls fetchTasks on component mount (empty dependency array) and sets the local tasks state with the result. Provides initial data hydration for the SPA.

    Preconditions:
      - App component is mounted in the DOM
      - Backend API is reachable

    Postconditions:
      - Local tasks state is populated with all tasks from the backend
      - UI renders the full task list after fetch completes

    Errors:
      - fetch_failed (ApiError): fetchTasks throws ApiError on mount

    Side effects: none
    Idempotent: yes
    """
    ...

def resolveBaseUrl() -> str:
    """
    Pure helper in api.ts that resolves the backend base URL from import.meta.env.VITE_API_URL, falling back to 'http://localhost:8000'. Strips trailing slash if present.

    Postconditions:
      - Returned string is a valid URL without trailing slash
      - If VITE_API_URL is set, its value is used (trailing slash stripped)
      - If VITE_API_URL is not set, returns 'http://localhost:8000'

    Side effects: none
    Idempotent: yes
    """
    ...

async def parseErrorResponse(
    response: any,
) -> ApiError:
    """
    Internal helper in api.ts that parses a non-ok Response into an ApiError. Attempts to parse JSON body as ErrorResponse to extract detail; falls back to response.statusText if JSON parsing fails.

    Preconditions:
      - response.ok is false

    Postconditions:
      - Returned ApiError.statusCode matches response.status
      - Returned ApiError.detail is parsed from response body or falls back to statusText
      - Returned ApiError.message includes the detail string

    Side effects: none
    Idempotent: yes
    """
    ...

# ── REQUIRED EXPORTS ──────────────────────────────────
# Your implementation module MUST export ALL of these names
# with EXACTLY these spellings. Tests import them by name.
# __all__ = ['TaskStatus', 'Task', 'OptionalStr', 'TaskCreateRequest', 'TaskUpdateRequest', 'ErrorResponse', 'DeleteConfirmation', 'HealthResponse', 'ApiError', 'TaskListProps', 'TaskItemProps', 'TaskFormProps', 'ImportMetaEnv', 'StatusBadgeColorMap', 'OptionalString', 'string', 'fetchTasks', 'createTask', 'updateTask', 'deleteTask', 'healthCheck', 'resolveBaseUrl', 'parseErrorResponse']
